language: scala
scala:
  - 2.11.8
  - 2.12.1
before_script: export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
script: sbt clean coverage test coverageAggregate
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
    - ivan@vonnagy.net
after_success: "sbt coveralls"